# 注意：需要在hosts文件配置    127.0.0.1 slave1 slave2
server:
  port: 8761
spring:
  application:
    name: cluster-cloud-server
  profiles: slave1

eureka:
  instance:
    hostname: slave1
# 注册服务器的地址：服务提供者和服务消费者都要依赖这个地址
  client:
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
---
server:
  port: 8762
spring:
  application:
    name: cluster-cloud-server
  profiles: slave2

eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/
